full_fea_col <- list('unique_participant_id', 'case_type', 'field_office', 'unique_case_id',
'gender', 'birth_year', 'state_of_current_location', 'state_of_origin',
'victim_relief_date', 'aftercare_initiated_date',
'aftercare_closed_date', 'avg_economic_empowerment_score_intake',
'avg_health_score_intake', 'avg_housing_score_intake',
'avg_mental_wellbeing_score_intake', 'avg_protection_score_intake',
'avg_social_support_score_intake',
'economic_empowerment_and_education_services_count',
'health_services_count', 'housing_services_count',
'mental_wellbeing_services_count', 'protection_services_count',
'support_system_services_count',
'economic_empowerment_and_education_events_count',
'health_events_count', 'housing_events_count',
'mental_wellbeing_events_count', 'protection_events_count',
'support_system_events_count', 'journey_cluster',
'closed_within_target', 'time_to_closure', 'low_aso',
'successful_closure', 'dropout')

fea_col <- list('case_type', 'field_office',
'gender', 'birth_year', 'state_of_current_location', 'state_of_origin',
'victim_relief_date', 'aftercare_initiated_date',
'aftercare_closed_date', 'avg_economic_empowerment_score_intake',
'avg_health_score_intake', 'avg_housing_score_intake',
'avg_mental_wellbeing_score_intake', 'avg_protection_score_intake',
'avg_social_support_score_intake',
'economic_empowerment_and_education_services_count',
'health_services_count', 'housing_services_count',
'mental_wellbeing_services_count', 'protection_services_count',
'support_system_services_count',
'economic_empowerment_and_education_events_count',
'health_events_count', 'housing_events_count',
'mental_wellbeing_events_count', 'protection_events_count',
'support_system_events_count', 'journey_cluster')

tg_cols <- list('closed_within_target', 'time_to_closure', 'low_aso',
'successful_closure', 'dropout')
