version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    json_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    pipeline_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: json_formatter
        filename: logs/visualization/pipelines.log
        maxBytes: 1048576 # 1MB
        backupCount: 5
        encoding: utf8
        delay: True

loggers:
    kernelai.io:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kernelai.pipeline:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    kernelai.pipeline.viz_input:
        level: INFO
        handlers: [pipeline_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
